### PR TITLE
jsonString computed variable for MongoCursor

### PR DESCRIPTION
**Pull request by DavidSights**
Added convenience method for getting a JSON string from MongoCursor instances, or MongoCollection.find() results.

### CODE REVIEW

**Comment by DavidSights** [comment]
Basically just wanted to be able to do something like this:

```
guard let json = collection.find(query: BSON())?.jsonString else {
    // Find failed.
    return
}
```

**Comment by kjessup** [comment]
Is there a particular reason why the results are put into a Dict with a "data" key as opposed to returning a JSON array?

**Comment by DavidSights** [comment]
@kjessup Not at all. I have no experience with constructing JSON, and just lifted this from an example I found. Totally open to a better way to present the JSON data.

**Comment by DavidSights** [comment]
@kjessup Updated to remove dictionary with "data" key.

**Comment by kjessup** [comment]
OK, tagged as 2.0.7. Thank you!

**Comment by DavidSights** [comment]
@kjessup Thank you as well! Looking forward to more opportunities to contribute. 🙂

**Pull request merged**
